package com.chadbutz.pai.main;

import com.chadbutz.pai.model.Conversation;
import com.chadbutz.pai.model.ConversationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ConversationRepository conversationRepository;

	@RequestMapping(method = RequestMethod.GET,path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewConversation (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Conversation n = new Conversation();
		n.setName(name);
		n.setEmail(email);
		conversationRepository.save(n);
		return "Saved";
	}
	
	@RequestMapping(method = RequestMethod.GET,path="/all")
	public @ResponseBody Iterable<Conversation> getAllConversations() {
		// This returns a JSON or XML with the users
		return conversationRepository.findAll();
	}
}
